name: 'd8mspro Config'
description: 'Provides core components required by other features.'
type: module
core: 8.x
dependencies:
  - block
  - contact
  - features
  - file
  - language
  - menu_link_content
  - node
  - page_manager
  - panels
  - pathauto
  - shortcut
  - taxonomy
package: d8mspro
