bundle: d8mspro
excluded:
  - system.theme
  - language.mappings
  - language.negotiation
  - page_manager.page.home
  - page_manager.page_variant.home-panels_variant-0
  - pathauto.pattern.contents
required: true
