name: 'd8mspro Config'
description: 'Provides core components required by other features.'
type: module
core: 8.x
dependencies:
  - automated_cron
  - block
  - ckeditor
  - contact
  - editor
  - features
  - file
  - filter
  - language
  - locale
  - menu_link_content
  - node
  - page_manager
  - panels
  - pathauto
  - search
  - shortcut
  - system
  - taxonomy
  - text
  - user
  - video_embed_wysiwyg
  - views
package: d8mspro
core_incompatible: false
