bundle: d8mspro
excluded:
  - features.bundle.default
  - system.theme
  - language.mappings
  - language.negotiation
  - page_manager.page.home
  - page_manager.page_variant.home-panels_variant-0
required: true
